#!/usr/bin/env bash
#Install nginx on your web-01 server

apt-get update -y

# Install Nginx
apt-get install -y nginx

# Configure Nginx to listen on port 80 (if not already)
if ! grep -q "listen 80;" /etc/nginx/sites-available/default; then
    sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
    sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:80;/' /etc/nginx/sites-available/default
fi

# Set the desired content for the root page
echo "Holberton School" > /var/www/html/index.html

# Restart Nginx without systemctl
/etc/init.d/nginx restart
